name: Bug-Report
description: Melde einen Bug!
labels: ['bug']

body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibe dein Problem!
      description: Beschreibe dein Problem genau!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduktionsschritte
      description: Beschreibe, wie man den Fehler reproduzieren kann.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
      description: Was sollte eigentlich passieren?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Weitere Informationen
      description: Screenshots, Videos etc.
  - type: input
    id: os
    attributes:
      label: Betriebsystem
      description: Dein Betriebsystem
      placeholder: e.g. Windows 10 oder 11 usw.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Dein Character-Name
      description: Wie lautet dein Charakter-Name?
      placeholder: e.g. Max Mustermann
    validations:
      required: false